name: REVIEW COMMENT
description: Issue voor registreren van reviewcommentaar op een RFC
title: "[neem het RFC nummer hier of de titel]"
labels: ["netwerk"]
body:
  - type: textarea
    id: issue_link
    attributes:
      label: Link naar Issue van RFC
      placeholder: "Neem hier de verwijzing op naar het het Issue van de RFC (tip: toets '[' + '#' dan verschijnt er een smart-list)"
    validations:
      required: true
  - type: textarea
    id: opmerkingen
    attributes:
      label: Onderwerp
      placeholder: Ruimte voor opmerkingen op de RFC
    validations:
      required: true
