name: MD to PDF (DGW)
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - main
    # Paths can be used to only trigger actions when you have edited certain files, such as a file within the /docs directory
    paths:
      - 'RFC_test/**.md'
      # - 'docs/images/**'

jobs:
  converttopdf:
    name: Build PDF
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: Markdown to PDF and HTML
        uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_path: RFC_test
          output_dir: RFC_pdf
          images_dir: plantUMLsrc
          build_html: false
      - uses: actions/upload-artifact@v3
        with:
          # name: upload
          path: RFC_pdf/

