name: Convert MD to PDF puppeteer

on:
  push:
    branches:
      - main # Adjust the branch name as needed

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install Pandoc
      run: sudo apt-get install pandoc -y

    - name: Convert MD to HTML
      run: pandoc -o RFC_pdf/output.html RFC_test/*.md

    - name: Install Puppeteer
      run: npm install puppeteer

    - name: Make script executable
      run: chmod +x .github/workflows/convert.js

    - name: Convert HTML to PDF
      run: |
        .github/workflows/convert.js
