name: Pandoc PDF Conversion

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Pandoc
        run: |
          sudo apt-get update -qy
          sudo apt-get install -qy pandoc

      - name: Install TeX Live
        run: |
          sudo apt-get install -qy texlive-xetex  # Installs TeX Live with XeTeX (PDF engine)

      - name: Convert to PDF
        run: |
          pandoc RFC_test/MDTEST.md -o RFC_test/MDTEST.pdf

      - name: List files in directory after conversion
        run: ls -R RFC_test
