name: Pandoc PDF Conversion

on:
    push:
      branches:
        - main

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Pandoc
        run: |
          sudo apt-get update -qy
          sudo apt-get install -qy pandoc

      - name: Install TeX Live with XeTeX (PDF engine)
        run: |
          sudo apt-get install -qy texlive-xetex

      - name: Set Permissions for RFC_test dir
        run: |
          chmod -R 755 RFC_test

      - name: Convert to PDF
        run: |
          pandoc RFC_test/MDTEST.md -o RFC_test/MDTEST.pdf

 #     - name: Copy PDF to repository
 #       run: |
 #         cp RFC_test/MDTEST.pdf $GITHUB_WORKSPACE/RFC_test/MDTEST.pdf

      - name: List files in directory after conversion (Debug)
        run: ls -R RFC_test

      - name: Commit and push PDF
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add RFC_test/MDTEST.pdf
          git commit -m "Add PDF file"
          git push
