name: Pandoc PDF Conversion

on: push

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Pandoc
        run: |
          sudo apt-get update -qy
          sudo apt-get install -qy pandoc

      - name: Convert to PDF
        run: |
          pandoc RFC_test/MDTEST.md -o RFC_test/MDTEST.pdf